DROP TABLE IF EXISTS pinned;

CREATE TABLE IF NOT EXISTS pinned (
  id SERIAL PRIMARY KEY,
  photo_id VARCHAR(16) NOT NULL UNIQUE,
  blur_hash VARCHAR(50) NOT NULL,
  raw_url TEXT NOT NULL UNIQUE,
  small_url TEXT NOT NULL UNIQUE,
  pinned_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);